connection:
    username: admin
    remoteAddress: 192.168.1.1 

spring:
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        hibernate:
            ddl-auto: validate
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://192.168.99.100:32768/production
        username: sylvain
        password: dubai
